pipeline {
    agent any
    stages{
        stage('workspace_clean'){
        }
        stage('pull'){
            steps{
                sh 'git clone https://github.com/ahvnavs/MVP.git'
            }
        }
        stage('docker build'){
            steps{
                sh 'cd infra'
                sh 'docker copmose up -d --build'
            }
        }
    }
}
