pipeline {
    agent any

    stages {

        stage('workspace_clean') {
            steps {
                cleanWs()
            }
        }

        stage('pull') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/ahvnavs/MVP.git'
            }
        }

        stage('docker build') {
            steps {
                dir('infra') {
                    sh 'docker compose up -d --build'
                }
            }
        }
    }
}
