pipeline {
    agent any
    stages{
        stage('workspace_clean'){
        }
        stage('pull'){
            sh 'git clone https://github.com/ahvnavs/MVP.git'
        }
        stage('docker build'){
            sh 'cd infra'
            sh 'docker copmose up -d --build'
        }
    }
}
